services:
  php1:
    build:
      context: ./php
    volumes:
      - ./app/TP-Final-3IW-ESGI-main:/var/www/html
      - ./app/TP-Final-3IW-ESGI-main/.env:/var/www/html/.env
    working_dir: /var/www/html
    command: sh -c "/start.sh --migrate"

  php2:
    build:
      context: ./php
    volumes:
      - ./app/TP-Final-3IW-ESGI-main:/var/www/html
      - ./app/TP-Final-3IW-ESGI-main/.env:/var/www/html/.env
    working_dir: /var/www/html
    command: sh -c "/start.sh"
  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/ConfigNGINX1.conf:/etc/nginx/conf.d/nginx.conf
      - ./app/TP-Final-3IW-ESGI-main:/var/www/html
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    restart: always

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/ConfigNGINX2.conf:/etc/nginx/conf.d/nginx.conf
      - ./app/TP-Final-3IW-ESGI-main:/var/www/html
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    restart: always

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: